# Generated by Django 4.1.5 on 2023-01-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='docs',
            field=models.FileField(upload_to='resume/docs'),
        ),
    ]
