# Generated by Django 4.1.5 on 2023-01-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
