# Generated by Django 4.1.5 on 2023-02-17 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_contact_amount_contact_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='resume/proof')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.contact')),
            ],
        ),
    ]
