# Generated by Django 4.1.5 on 2023-02-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
