# Generated by Django 4.1.5 on 2023-02-17 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_proof_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='r_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='resume.resume'),
        ),
    ]
