# Generated by Django 4.1.5 on 2023-02-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_remove_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
