# Generated by Django 4.1.5 on 2023-02-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_proof_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
