# Generated by Django 4.1.5 on 2023-02-18 04:49

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_proof_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='b_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proof',
            name='d_date',
            field=models.DateField(blank=True, default=datetime.date.today),
            preserve_default=False,
        ),
    ]
