# Generated by Django 4.1.5 on 2023-02-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_proof_b_date_proof_d_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='d_date',
            field=models.DateField(),
        ),
    ]
