# Generated by Django 4.1.5 on 2023-02-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_alter_proof_d_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='d_date',
            field=models.DateField(blank=True),
        ),
    ]
