# Generated by Django 4.1.5 on 2023-02-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_alter_proof_d_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
