# Generated by Django 4.1.5 on 2023-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_alter_proof_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=50)),
                ('img', models.ImageField(upload_to='resume/profile')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('github_link', models.CharField(max_length=50)),
                ('linkedin_link', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('s_year', models.CharField(max_length=10)),
                ('e_year', models.CharField(max_length=10)),
                ('degree', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=50)),
                ('tenth_age', models.CharField(max_length=10)),
                ('twelth_age', models.CharField(max_length=10)),
                ('about', models.TextField()),
                ('skills', models.TextField()),
                ('achievement', models.TextField()),
                ('projects', models.TextField()),
                ('exprience', models.TextField()),
                ('hobbies', models.TextField()),
                ('other', models.TextField()),
            ],
        ),
    ]
