# Generated by Django 4.1.5 on 2023-02-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='college',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='degree',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='e_year',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='fname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='github_link',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='linkedin_link',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='lname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='s_year',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='stream',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='tenth_age',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='twelth_age',
            field=models.CharField(default='', max_length=10),
        ),
    ]
