# Generated by Django 4.1.5 on 2023-02-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_alter_user_profile_city_alter_user_profile_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
