# Generated by Django 4.1.5 on 2023-02-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_user_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='docs',
        ),
    ]
